# Generated by Django 3.1 on 2020-10-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_auto_20200830_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.IntegerField(default='0', verbose_name='Номер телефона:'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='message',
            name='company',
            field=models.CharField(max_length=250, verbose_name='Имя Фамилия:'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.CharField(max_length=250, verbose_name='Телефон:'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=2000, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='work',
            name='instruments',
            field=models.TextField(blank='True', max_length=2000),
        ),
    ]
