# Generated by Django 3.1 on 2020-10-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_auto_20201010_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='company',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='contact',
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='none@gmail.com', max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.IntegerField(default='380', verbose_name='Номер телефона:'),
        ),
    ]
